config/routes.rb
Rails.application.routes.draw do
  resources :treeweathers
  resources :weathers
  post 'posts/:id', to: "posts#create", as: "post"
  resources :trees
  devise_for :users
  resources :users, only: [:show]
  post 'contributions/:id', to: 'contributions#create', as: 'create_contribution'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contribution.rb
class Contribution < ApplicationRecord
  belongs_to :user
  belongs_to :tree
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :posteable, polymorphic: true
end

app/models/tree.rb
class Tree < ApplicationRecord
    has_many :contributions
    has_many :users, through: :contributions
    has_many :posts, as: :posteable
    has_many :treeweathers
    has_many :weathers, through: :treeweathers
    has_many_attached :images

    def getWeather
        self.weathers.pluck(:name).join(', ')
    end
end

app/models/treeweather.rb
class Treeweather < ApplicationRecord
  belongs_to :tree
  belongs_to :weather
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
  has_many :contributions
  has_many :trees, through: :contributions
  has_many :posts, as: :posteable
  has_many :treeweathers
  has_many :weathers, through: :treeweathers

end

app/models/weather.rb
class Weather < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :avatar])
    end
  end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController
    def create
        user = current_user
        tree = Tree.find(params[:id])
        amount = '1000'

        Contribution.create(user: user, tree: tree, amount: amount)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def create
        @post = Post.create(content: params[:content], posteable_type: params[:class], posteable_id: params[:id]) 

        params[:class] == 'User' ? (redirect_to user_path(params[:id])) : (redirect_to tree_path(params[:id]))
    end
end

app/controllers/trees_controller.rb
class TreesController < ApplicationController
  before_action :set_tree, only: [:show, :edit, :update, :destroy]

  # GET /trees
  # GET /trees.json
  def index
    @trees = Tree.all
  end

  # GET /trees/1
  # GET /trees/1.json
  def show
  end

  # GET /trees/new
  def new
    @tree = Tree.new
  end

  # GET /trees/1/edit
  def edit
  end

  # POST /trees
  # POST /trees.json
  def create
    @tree = Tree.new(tree_params)
    respond_to do |format|
      if @tree.save
        tree_params[:weather_ids].reject(&:empty?).each{|id| Treeweather.create(tree_id: @tree.id, weather_id: id)}
        format.html { redirect_to @tree, notice: 'Tree was successfully created.' }
        format.json { render :show, status: :created, location: @tree }
      else
        format.html { render :new }
        format.json { render json: @tree.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trees/1
  # PATCH/PUT /trees/1.json
  def update
    respond_to do |format|
      if @tree.update(tree_params)
        format.html { redirect_to @tree, notice: 'Tree was successfully updated.' }
        format.json { render :show, status: :ok, location: @tree }
      else
        format.html { render :edit }
        format.json { render json: @tree.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trees/1
  # DELETE /trees/1.json
  def destroy
    @tree.destroy
    respond_to do |format|
      format.html { redirect_to trees_url, notice: 'Tree was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tree
      @tree = Tree.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tree_params
      params.require(:tree).permit(:name, {weather_ids: []}, images: [])
    end
end

app/controllers/treeweathers_controller.rb
class TreeweathersController < ApplicationController
  before_action :set_treeweather, only: [:show, :edit, :update, :destroy]

  # GET /treeweathers
  # GET /treeweathers.json
  def index
    @treeweathers = Treeweather.all
  end

  # GET /treeweathers/1
  # GET /treeweathers/1.json
  def show
  end

  # GET /treeweathers/new
  def new
    @treeweather = Treeweather.new
  end

  # GET /treeweathers/1/edit
  def edit
  end

  # POST /treeweathers
  # POST /treeweathers.json
  def create
    @treeweather = Treeweather.new(treeweather_params)

    respond_to do |format|
      if @treeweather.save
        format.html { redirect_to @treeweather, notice: 'Treeweather was successfully created.' }
        format.json { render :show, status: :created, location: @treeweather }
      else
        format.html { render :new }
        format.json { render json: @treeweather.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /treeweathers/1
  # PATCH/PUT /treeweathers/1.json
  def update
    respond_to do |format|
      if @treeweather.update(treeweather_params)
        format.html { redirect_to @treeweather, notice: 'Treeweather was successfully updated.' }
        format.json { render :show, status: :ok, location: @treeweather }
      else
        format.html { render :edit }
        format.json { render json: @treeweather.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /treeweathers/1
  # DELETE /treeweathers/1.json
  def destroy
    @treeweather.destroy
    respond_to do |format|
      format.html { redirect_to treeweathers_url, notice: 'Treeweather was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_treeweather
      @treeweather = Treeweather.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def treeweather_params
      params.require(:treeweather).permit(:tree_id, :weather_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id])
        @trees = Tree.all
    end
end

app/controllers/weathers_controller.rb
class WeathersController < ApplicationController
  before_action :set_weather, only: [:show, :edit, :update, :destroy]

  # GET /weathers
  # GET /weathers.json
  def index
    @weathers = Weather.all
  end

  # GET /weathers/1
  # GET /weathers/1.json
  def show
  end

  # GET /weathers/new
  def new
    @weather = Weather.new
  end

  # GET /weathers/1/edit
  def edit
  end

  # POST /weathers
  # POST /weathers.json
  def create
    @weather = Weather.new(weather_params)

    respond_to do |format|
      if @weather.save
        format.html { redirect_to @weather, notice: 'Weather was successfully created.' }
        format.json { render :show, status: :created, location: @weather }
      else
        format.html { render :new }
        format.json { render json: @weather.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weathers/1
  # PATCH/PUT /weathers/1.json
  def update
    respond_to do |format|
      if @weather.update(weather_params)
        format.html { redirect_to @weather, notice: 'Weather was successfully updated.' }
        format.json { render :show, status: :ok, location: @weather }
      else
        format.html { render :edit }
        format.json { render json: @weather.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weathers/1
  # DELETE /weathers/1.json
  def destroy
    @weather.destroy
    respond_to do |format|
      format.html { redirect_to weathers_url, notice: 'Weather was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weather
      @weather = Weather.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def weather_params
      params.require(:weather).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trees_helper.rb
module TreesHelper
end

app/helpers/treeweathers_helper.rb
module TreeweathersHelper
end

app/helpers/weathers_helper.rb
module WeathersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EcoFriendlyProyect</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar'%>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse offset-md-10" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto align-item-left">
      <li class="nav-item dropdown navbar-right">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Session
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <ul>
                <% if current_user %>
                    <li class="nav-item">
                        <%= link_to "Salir", destroy_user_session_path, method: :delete %>
                    </li>
                <% else %>
                    <li class="nav-item">
                        <%= link_to "Registro", new_user_registration_path %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "ingreso", new_user_session_path %>
                    </li>
                <% end %>
            </ul>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/trees/_form.html.erb
<%= form_with(model: tree, local: true) do |form| %>
  <% if tree.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tree.errors.count, "error") %> prohibited this tree from being saved:</h2>

      <ul>
        <% tree.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :images %>
    <%= form.file_field :images, multiple: true %>
  </div>

  <div class="field">
    <%= form.label :weathers %>
    <%= form.collection_check_boxes(:weather_ids, Weather.all, :id, :name) do |b| %>
      <%= b.label class: "checkbox" do %>
        <%= b.check_box + b.text %>
      <% end %>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/trees/edit.html.erb
<h1>Editing Tree</h1>

<%= render 'form', tree: @tree %>

<%= link_to 'Show', @tree %> |
<%= link_to 'Back', trees_path %>

app/views/trees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Climas</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trees.each do |tree| %>
      <tr>
        <td><%= tree.name %></td>
        <td><%= tree.getWeather %></td>
        <td><%= link_to 'Show', tree %></td>
        <td><%= link_to 'Edit', edit_tree_path(tree) %></td>
        <td><%= link_to 'Destroy', tree, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<>

<%= link_to 'New Tree', new_tree_path %>

app/views/trees/new.html.erb
<h1>New Tree</h1>

<%= render 'form', tree: @tree %>

<%= link_to 'Back', trees_path %>

app/views/trees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tree.name %>
</p>

<% @tree.images.each do |img| %>
  <%= image_tag img, size: "200x200"%>
<% end %>

  <div class="row">
      <%= form_with(url: post_path(@tree), local: true) do |f| %>
          <%= f.hidden_field :class, value: @tree.class %>
          <%= f.text_field :content , placeholder: 'ingresa tu post'%>
          <%= f.submit 'comentar'%>
      <% end %>
      <% @tree.posts.each do |post| %>
          <%= post.content %>
      <% end %>
  </div>

<%= link_to 'Edit', edit_tree_path(@tree) %> |
<%= link_to 'Back', trees_path %>

app/views/treeweathers/_form.html.erb
<%= form_with(model: treeweather, local: true) do |form| %>
  <% if treeweather.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(treeweather.errors.count, "error") %> prohibited this treeweather from being saved:</h2>

      <ul>
        <% treeweather.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tree_id %>
    <%= form.text_field :tree_id %>
  </div>

  <div class="field">
    <%= form.label :weather_id %>
    <%= form.text_field :weather_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/treeweathers/edit.html.erb
<h1>Editing Treeweather</h1>

<%= render 'form', treeweather: @treeweather %>

<%= link_to 'Show', @treeweather %> |
<%= link_to 'Back', treeweathers_path %>

app/views/treeweathers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Treeweathers</h1>

<table>
  <thead>
    <tr>
      <th>Tree</th>
      <th>Weather</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @treeweathers.each do |treeweather| %>
      <tr>
        <td><%= treeweather.tree_id %></td>
        <td><%= treeweather.weather_id %></td>
        <td><%= link_to 'Show', treeweather %></td>
        <td><%= link_to 'Edit', edit_treeweather_path(treeweather) %></td>
        <td><%= link_to 'Destroy', treeweather, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Treeweather', new_treeweather_path %>

app/views/treeweathers/new.html.erb
<h1>New Treeweather</h1>

<%= render 'form', treeweather: @treeweather %>

<%= link_to 'Back', treeweathers_path %>

app/views/treeweathers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tree:</strong>
  <%= @treeweather.tree_id %>
</p>

<p>
  <strong>Weather:</strong>
  <%= @treeweather.weather_id %>
</p>

<%= link_to 'Edit', edit_treeweather_path(@treeweather) %> |
<%= link_to 'Back', treeweathers_path %>

app/views/users/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-4">
            <h2><%= @user.name%></h2>
            <div>
                <% if @user.avatar.attached? %>
                    <%= image_tag @user.avatar, size: "200x200"%>
                <% else %>
                    imagen random
                <% end %>
            </div>
        </div>
        <div class="col-8">
            <div class="row">
                <% @trees.each do |tree| %>
                    <%= tree.name %>
                    <%= link_to "aporta ahora!", create_contribution_path(tree), method: :post %>
                <% end %>
            </div>
            <div class="row">
                <%= form_with(url: post_path(@user), local: true) do |f| %>
                    <%= f.hidden_field :class, value: @user.class %>
                    <%= f.text_field :content , placeholder: 'ingresa tu post'%>
                    <%= f.submit 'comentar'%>
                <% end %>

                <% @user.posts.each do |post| %>
                    <%= post.content %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/weathers/_form.html.erb
<%= form_with(model: weather, local: true) do |form| %>
  <% if weather.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(weather.errors.count, "error") %> prohibited this weather from being saved:</h2>

      <ul>
        <% weather.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/weathers/edit.html.erb
<h1>Editing Weather</h1>

<%= render 'form', weather: @weather %>

<%= link_to 'Show', @weather %> |
<%= link_to 'Back', weathers_path %>

app/views/weathers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Weathers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @weathers.each do |weather| %>
      <tr>
        <td><%= weather.name %></td>
        <td><%= link_to 'Show', weather %></td>
        <td><%= link_to 'Edit', edit_weather_path(weather) %></td>
        <td><%= link_to 'Destroy', weather, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Weather', new_weather_path %>

app/views/weathers/new.html.erb
<h1>New Weather</h1>

<%= render 'form', weather: @weather %>

<%= link_to 'Back', weathers_path %>

app/views/weathers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @weather.name %>
</p>

<%= link_to 'Edit', edit_weather_path(@weather) %> |
<%= link_to 'Back', weathers_path %>